delete from vehicle;
-- *** CARS *** --
--Volvo
--S60
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'I', 'Petrol', '2.0 i T 180KM 132kW', '132kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'I', 'Petrol', '2.0 T 180KM 132kW', '132kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'I', 'Petrol', '2.3 T5 20V 250KM 184kW', '184W', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'I', 'Petrol', '2.4 i 20V T5 260KM 191kW', '191kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'I', 'Petrol', '2.4 20V 140KM 103kW', '103kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'I', 'Petrol', '2.4 i 20V 170KM 125kW', '125kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'I', 'Petrol', '2.4 AWD 200KM 147kW', '147kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'I', 'Petrol', '2.4 T 200KM 147kW', '147kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'I', 'Petrol', '2.4 20V 210KM 154kW', '154kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'I', 'Petrol', '2.5 185KM 136kW', '136kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'I', 'Petrol', '2.5T i 20V 210KM 154kW', '154kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'I', 'Petrol', '2.5 i 20V AWD R 300KM 221kW', '221kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'I', 'Diesel', '2.4 TD DPF 126KM 93kW', '93kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'I', 'Diesel', '2.4 D5 130KM 96kW', '96kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'I', 'Diesel', '2.4 D5 163KM 120kW', '120kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'I', 'Diesel', '2.4 D5 185KM 136kW', '136kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Petrol', '1.5 T3 DRIVE-E 152KM 112kW', '112kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Petrol', '1.6 T3 150KM 110kW', '110kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Petrol', '1.6 T4 180KM 132kW', '132kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Petrol', '2.0 T3 DRIVE-E 152KM 112kW', '112kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Petrol', '2.0 T4 DRIVE-E 190KM 140kW', '140kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Petrol', '2.0 T5 245KM 180kW', '180kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Petrol', '2.0 T5 DRIVE-E 245KM 180kW', '180kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Petrol', '2.0 T 203KM 149kW', '149kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Petrol', '2.0 T5 240KM 177kW', '177kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Petrol', '2.5 T5 254KM 187kW', '187kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Petrol', '3.0 T6 304KM 224kW', '224kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Diesel', '1.6 D2 115KM 85kW', '85kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Diesel', '2.0 D2 DRIVE-E 120KM 88kW', '88kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Diesel', '2.0 D3 DRIVE-E 150KM 110kW', '110kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Diesel', '2.0 D4 DRIVE-E 181KM 133kW', '133kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Diesel', '2.0 D4 DRIVE-E 190KM 140kW', '140kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Diesel', '2.0 D5 DRIVE-E 225KM 165kW', '165kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Diesel', '2.0 D3 136KM 100kW', '100kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Diesel', '2.0 D3 163KM 120kW', '120kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Diesel', '2.0 D4 163KM 120kW', '120kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Diesel', '2.4 D4 190KM 140kW', '140kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Diesel', '2.4 D4 DRIVE-E 190KM 140kW', '140kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'II', 'Diesel', '2.4 D5 215KM 158kW', '158kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'III', 'Petrol', '2.0 T4 190KM 140kW', '140kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'III', 'Petrol', '2.0 T5 250KM 184kW', '184kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'III', 'Petrol', '2.0 T5 254KM 187kW', '187kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'III', 'Petrol', '2.0 T6 310KM 228kW', '228kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'III', 'Hybrid', '2.0 B4 Mild Hybrid 211KM 155kW', '155kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'III', 'Hybrid', '2.0 B5 Mild Hybrid 264KM 194kW', '194kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S60', 'III', 'Hybrid', '2.0 T8 Twin Engine Plug-In Hybrid 405KM 298kW', '298kW', 'I', 'true');
--S90
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S90', 'I', 'Petrol', '3.0 24V 204KM 150kW', '150kW', 'II', 'false');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S90', 'I', 'Petrol', '2.0 T5 250KM 184kW', '184kW', 'II', 'false');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S90', 'II', 'Petrol', '2.0 T5 254KM 187kW', '187kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S90', 'II', 'Petrol', '2.0 T6 310KM 228kW', '228kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S90', 'II', 'Petrol', '2.0 T6 320KM 235kW', '235kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S90', 'II', 'Petrol', '2.0 T8 407KM 299kW', '299kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S90', 'II', 'Diesel', '2.0 D4 190KM 140kW', '140kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S90', 'II', 'Diesel', '2.0 D5 235KM 173kW', '173kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S90', 'II', 'Diesel', '2.0 D3 150KM 110kW', '110kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S90', 'II', 'Hybrid', '2.0 T8 390KM 287kW', '287kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S90', 'II', 'Hybrid', '2.0 T8 Plug-In Hybrid 391KM 288kW', '288kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Volvo', 'S90', 'II', 'Hybrid', '2.0 T8 Twin Engine 391KM 288kW', '288kW', 'I', 'true');

--Honda
--NSX
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'NSX', 'I', 'Petrol', '3.0 24V 273KM 201kW', '201kW', 'III', 'false');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES('CAR', 'Honda', 'NSX', 'I', 'Petrol', '3.2 24V 280KM 206kW', '206kW', 'III', 'false');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'NSX', 'I', 'Petrol', '3.0 24V Automatic 256KM 188kW', '188kW', 'III', 'false');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'NSX', 'II', 'Hybrid', '3.5 V6 573KM 421kW', '421kW', 'III', 'false');
--CR-V
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'CR-V', 'I', 'Petrol', '2.0 16V RD1 128KM 94kW', '94kW', 'II', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'CR-V', 'I', 'Petrol', '2.0 16V 147KM 108kW', '108kW', 'II', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'CR-V', 'II', 'Petrol', '2.0 16V 150KM 110kW', '110kW', 'II', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'CR-V', 'II', 'Petrol', '2.4 i 16V LX 162KM 119kW', '119kW', 'II', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'CR-V', 'II', 'Diesel', '2.2 TD 140KM 103kW', '103kW', 'II', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'CR-V', 'III', 'Petrol', '2.0 i-VTEC 150KM 110kW', '110kW', 'II', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'CR-V', 'III', 'Petrol', '2.4 i-VTEC 170KM 125kW', '125kW', 'II', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'CR-V', 'III', 'Diesel', '2.2 i-CDTi 150KM 110kW', '110kW', 'II', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'CR-V', 'III', 'Diesel', '2.2 i-CDTi 140KM 103kW', '103kW', 'II', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'CR-V', 'IV', 'Petrol', '2.0 i-VTEC 155KM 114kW', '114kW', 'II', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'CR-V', 'IV', 'Petrol', '2.4 188KM 138kW', '138kW', 'II', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'CR-V', 'IV', 'Petrol', '2.4 185KM 136kW', '136kW', 'II', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'CR-V', 'IV', 'Diesel', '1.6 i-DTEC 120KM 88kW', '88kW', 'II', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'CR-V', 'IV', 'Diesel', '1.6 i-DTEC 160KM 118kW', '118kW', 'II', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'CR-V', 'IV', 'Diesel', '2.2 i-DTEC 150KM 110kW', '110kW', 'II', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'CR-V', 'V', 'Petrol', '1.5 VTEC TURBO 173KM 127kW', '127kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'CR-V', 'V', 'Petrol', '1.5 VTEC TURBO 193KM 142kW', '142kW', 'I', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('CAR', 'Honda', 'CR-V', 'V', 'Petrol', '2.0 i-MMD 184KM 135kW', '135kW', 'I', 'true');

-- *** MOTORBIKES *** --
--Honda
--CBF
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('MTB', 'Honda', 'CBF', 'I', 'Petrol', '599cc liquid-cooled 4-stroke 16-valve', '71kW', 'III', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('MTB', 'Honda', 'CBF', 'II', 'Petrol', '599cc liquid-cooled 4-stroke 16-valve', '70kW', 'III', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('MTB', 'Honda', 'CBF', 'III', 'Petrol', '599cc liquid-cooled 4-stroke 16-valve', '70kW', 'III', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('MTB', 'Honda', 'CBF', 'IV', 'Petrol', '599cc liquid-cooled 4-stroke 16-valve', '71kW', 'III', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('MTB', 'Honda', 'CBF', 'V', 'Petrol', '599cc liquid-cooled 4-stroke 16-valve', '76kW', 'III', 'true');
--CBR
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('MTB', 'Honda', 'CBR', 'I', 'Petrol', '599 cc liquid-cooled inline four-cylinder', '80kW', 'II', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('MTB', 'Honda', 'CBR', 'II', 'Petrol', '599 cc liquid-cooled inline four-cylinder', '79kW', 'II', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('MTB', 'Honda', 'CBR', 'III', 'Petrol', '599 cc liquid-cooled inline four-cylinder', '79kW', 'II', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('MTB', 'Honda', 'CBR', 'IV', 'Petrol', '599 cc liquid-cooled inline four-cylinder', '74kW', 'II', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('MTB', 'Honda', 'CBR', 'V', 'Petrol', '599 cc liquid-cooled inline four-cylinder', '75kW', 'II', 'true');

-- *** TRAILERS *** --
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('TRA', 'Besttrailers', 'Loader', 'null', 'null', 'null', 'null', 'null', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('TRA', 'EMTECH', 'PC24', 'null', 'null', 'null', 'null', 'null', 'true');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('TRA', 'Fendt', 'OPAL 550', 'null', 'null', 'null', 'null', 'null', 'false');
INSERT INTO vehicle (VEHICLE_TYPE, BRAND, VEHICLE_MODEL, GENERATION, ENGINE_TYPE, ENGINE, POWER, PROTECTION_CLASS, PARTS_AVAILABILITY) VALUES ('TRA', 'Nooteboom', 'OBV-55-03v', 'null', 'null', 'null', 'null', 'null', 'true');

